exclude_path = [
	"site/custom/partials/",
	"docs/custom/partials/"
]
cache = true
max_cache_age = "2w"
user_agent = "curl/8.11.1"
timeout = 20
max_retries = 2
retry_wait_time = 5
require_https = true
exclude_mail = true
