name: Offline Check for dead links

on:
  push:

permissions:
  contents: read

jobs:
  link-check:
    name: Offline Link Check
    runs-on: ubuntu-latest
    steps:            
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-static-i18n[material]

      - name: Build
        run: mkdocs build

      - name: Check offline links
        uses: lycheeverse/lychee-action@v2.0.2
        with:
          args: --config lychee.toml --no-progress --offline '**/*.html'
          fail: true
